$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      services:
        - docker
        - name: vscode
          options:
            onlyPreview: true
            launch: bash .cnb/preview-launch.sh
            keepAliveTimeout: 18h
            daemon: false
            backup: true
