$:
  vscode:
    - runner:
        cpus: 2
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: install
          script:
            - bun install --frozen-lockfile
            - bun run build:web
        - name: start-relay
          script:
            - bash .cnb/preview-launch.sh
